name: Update Next.js Dependency

on:
  schedule:
    - cron: '0 0 * * 1'  # Exécution tous les lundis à minuit
  workflow_dispatch:  # Permet de déclencher manuellement

# Ajout des permissions nécessaires
permissions:
  contents: write
  pull-requests: write

jobs:
  update-nextjs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      - name: Check for Next.js updates
        id: check-updates
        run: |
          npm i -g npm-check-updates
          UPDATES=$(npx npm-check-updates next --target latest --format json)
          if [[ $UPDATES == *"next"* ]]; then
            echo "has_updates=true" >> $GITHUB_OUTPUT
            echo "updates<<EOF" >> $GITHUB_OUTPUT
            echo "$UPDATES" >> $GITHUB_OUTPUT
            echo "EOF" >> $GITHUB_OUTPUT
          else
            echo "has_updates=false" >> $GITHUB_OUTPUT
          fi

      - name: Update Next.js
        if: steps.check-updates.outputs.has_updates == 'true'
        run: |
          npx npm-check-updates next -u
          npm install

      - name: Run tests
        if: steps.check-updates.outputs.has_updates == 'true'
        run: npm test
        continue-on-error: true
        
      - name: Run linting
        if: steps.check-updates.outputs.has_updates == 'true'
        id: lint
        run: |
          mkdir -p logs
          npx next lint > logs/lint-results.log 2>&1 || true
          if grep -q "error" logs/lint-results.log; then
            echo "lint_errors=true" >> $GITHUB_OUTPUT
            LINT_ERRORS=$(cat logs/lint-results.log)
            echo "lint_errors_content<<EOF" >> $GITHUB_OUTPUT
            echo "$LINT_ERRORS" >> $GITHUB_OUTPUT
            echo "EOF" >> $GITHUB_OUTPUT
          else
            echo "lint_errors=false" >> $GITHUB_OUTPUT
          fi

      - name: Add lint results to PR
        if: steps.check-updates.outputs.has_updates == 'true' && steps.lint.outputs.lint_errors == 'true'
        run: |
          echo "### ⚠️ Lint Errors Detected" >> lint-report.md
          echo "Des erreurs de linting ont été détectées après la mise à jour de Next.js:" >> lint-report.md
          echo "```" >> lint-report.md
          cat logs/lint-results.log >> lint-report.md
          echo "```" >> lint-report.md

      - name: Create Pull Request
        if: steps.check-updates.outputs.has_updates == 'true'
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "chore: update Next.js to latest version"
          title: "⬆️ Update Next.js to latest version"
          body: |
            Mise à jour automatique de Next.js vers la dernière version.
            
            Cette PR a été créée automatiquement par le workflow GitHub Action.
            
            ${{ steps.lint.outputs.lint_errors == 'true' && '⚠️ **Attention:** Des erreurs de linting ont été détectées. Consultez le rapport de lint dans les fichiers de la PR.' || '✅ Lint check passed successfully.' }}
          branch: update-nextjs
          base: main
          labels: |
            dependencies
            automated-pr 